name: Sync GXDE Mirror

on:
  workflow_dispatch:

jobs:  
  build:
    name: Sync
    runs-on: ubuntu-24.04
    steps:
      # 由于默认的 Ubuntu 环境只有 17G 左右的剩余空间，所以我们需要先利用如下 action 对编译环境进行扩容
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # 这个值是保留给系统的空间大小，之前设置太小，总会在安装依赖或者编译过程中报设备空间不足的错误而导致编译失败
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
          remove-android: 'true'

      - name: Clone Repository
        env:
          GITHUBUSER: ${{ secrets.GITHUBUSER }}
          GITHUBMAIL: ${{ secrets.GITHUBMAIL }}
          GITHUBTOCKEN: ${{ secrets.GITHUBTOCKEN }}
        run: |
          sudo apt update
          sudo apt install git -y
          git config --global user.name "$GITHUBUSER"
          git config --global user.email "$GITHUBMAIL"
          git clone https://$GITHUBUSER:$GITHUBTOCKEN@github.com/gfdgd-xi/gxde-os-mirror.git --depth=1
          git clone https://$GITHUBUSER:$GITHUBTOCKEN@github.com/gfdgd-xi/gxde-os-mirror-loader.git --depth=1

      - name: Sync
        env:
          RSYNCPASSWORD: ${{ secrets.RSYNCPASSWORD }}
          RSYNCURL: ${{ secrets.RSYNCURL }}
        run: |
          sudo apt install rsync -y
          echo $RSYNCPASSWORD > /tmp/password.pass
          chmod 600 /tmp/password.pass
          cp -rv gxde-os-mirror-loader/icons gxde-os-mirror
          cp -rv gxde-os-mirror-loader/40*.html gxde-os-mirror
          cp -rv gxde-os-mirror-loader/50*.html gxde-os-mirror
          rsync --progress --delay-updates --delete --exclude *.html -avpP --password-file=/tmp/password.pass -av  $RSYNCURL gxde-os-mirror --max-size=100m
          # 加载页面
          cd gxde-os-mirror
          python3 ../gxde-os-mirror-loader/build.py

      - name: Add git repo
        run: |
          cd gxde-os-mirror
          git add .
          git commit -m "Sync: $(date)"
          git push